name: Deploy on GitHub page

on:
  push:
    branches: ['main']

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: package.json
      - uses: actions/configure-pages@v2
        id: pages
        with:
          static_site_generator: gatsby
      - uses: actions/cache@v3
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-
      - name: Install dependencies
        run: yarn --immutable
      - name: Build with Gatsby
        env:
          PREFIX_PATHS: 'true'
        run: yarn run build
      - uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
      - uses: actions/deploy-pages@v1
        id: deployment
